### ISSUE TITLE
[BUG]Unknown encoder 'libamr_wb'

### ISSUE THREAD

**Issue by Dana-Iclucia-Forever** [khjxiaogu/MiraiSongPlugin#18]
在CentOS 8.0下，正确指定了ffmpeg（带有openlib-amrwb），但在进行点歌操作时出现错误，并在qq返回了“当前状态不支持音频”的消息。

复现：在centos下，进行点歌会出现此错误。但在设置中amrwb: false时能输出不清晰的声音

请求能够提供解决的办法，或者增加对ffmpeg高版本的支持

> ffmpeg version N-55863-g9f38fac053-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 64.100 / 56. 64.100
  libavcodec     58.119.100 / 58.119.100
  libavformat    58. 65.101 / 58. 65.101
  libavdevice    58. 11.103 / 58. 11.103
  libavfilter     7.100.100 /  7.100.100
  libswscale      5.  8.100 /  5.  8.100
  libswresample   3.  8.100 /  3.  8.100
  libpostproc    55.  8.100 / 55.  8.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/root/mcl/./temp/wv1612699822671.m4a':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2019-06-07T08:02:59.000000Z
    album           : 狂热节拍14TH
    artist          : Ryu☆
    iTunSMPB        :  00000000 00000A40 000001D1 000000000051C3EF 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    title           : Second Heaven
    encoder         : Nero AAC codec / 1.5.4.0
  Duration: 00:02:01.58, start: 0.059501, bitrate: 96 kb/s
    Chapter #0:0: start 0.059501, end 121.639179
    Metadata:
      title           : Second Heaven
    Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2019-06-07T08:02:59.000000Z
      handler_name    : Sound Media Handler
      vendor_id       : [0][0][0][0]
Unknown encoder 'libamr_wb'
2021-02-07 20:10:22 W/stderr: java.io.FileNotFoundException: ./temp/wv1612699822671.amr (No such file or directory)
2021-02-07 20:10:22 W/stderr:     at java.base/java.io.FileInputStream.open0(Native Method)
2021-02-07 20:10:22 W/stderr:     at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
2021-02-07 20:10:22 W/stderr:     at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
2021-02-07 20:10:22 W/stderr:     at com.khjxiaogu.MiraiSongPlugin.cardprovider.AmrVoiceProvider.process(AmrVoiceProvider.java:63)
2021-02-07 20:10:22 W/stderr:     at com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.lambda$makeSearchesTemplate$2(MiraiSongPlugin.java:162)
2021-02-07 20:10:22 W/stderr:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
2021-02-07 20:10:22 W/stderr:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
2021-02-07 20:10:22 W/stderr:     at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by chrysoljq** [comment]
我也遇到了这个问题，他默认输出的是我m4a后缀的语音而不是amr

**Comment by khjxiaogu** [comment]
可能是该ffmpeg分发时不带有libamr_wb的解码器，建议尝试自己编译或者更换ffmpeg版本。

**Comment by Dana-Iclucia-Forever** [comment]
> 
> 
> 可能是该ffmpeg分发时不带有libamr_wb的解码器，建议尝试自己编译或者更换ffmpeg版本。

自行编译过带libamr_wb静态库的了，但是问题依然没改变
环境是centos，目前还没尝试在windows下操作
