### ISSUE TITLE
执行点歌命令时报错

### ISSUE THREAD

**Issue by maqa588** [khjxiaogu/MiraiSongPlugin#19]
在执行#点歌指令时报错，但单独对某个平台进行点歌时可以执行

2021-02-12 20:26:59 E/main: Exception in coroutine <unnamed>
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:147)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$14$1.invoke(JvmMethodListenersInternal.kt:140)
        ... 7 more
Caused by: java.lang.IllegalArgumentException: 3 > 2
        at java.base/java.util.Arrays.copyOfRange(Unknown Source)
        at java.base/java.util.Arrays.copyOfRange(Unknown Source)
        at com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.lambda$onEnable$5(MiraiSongPlugin.java:202)
        at com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin$1.onFriend(MiraiSongPlugin.java:272)
        ... 12 more

另外请教一下在linux下为插件配置silk encoder的方法，谢谢！

**Comment by khjxiaogu** [comment]
点歌指令要有3个参数，您只输入了两个，所以不能正常点歌。
关于silk encoder，这个只是老版本的遗留，建议只用amr模式，效果比silk往往更好
