### ISSUE TITLE
关于Mirai点歌插件如何自定义指令的问题

### ISSUE THREAD

**Issue by MJZBlock** [khjxiaogu/MiraiSongPlugin#22]
亲爱的kjh小古：
      你好！
      我在GitHub上看见了您的点歌插件。使用下来感觉不错。但由于我个人没有代码基础（啥也不会）所以想向您请求几个问题和提出几个意见！
      问题：
      1、如何自定义指令？我应该怎么做？
      描述：我翻了一下Mirai的文件夹，加入jar后没有什么可以更改的地方。只有一个json和yml，所以要如何自定义指令请大佬详细给个教程。
      建议：
      1、插件很完美，希望能加上权限系统。就什么人可以点什么人不能点这样的。

      谢谢您了！

**Comment by Kwaiyu** [comment]
```
2021-06-18 21:03:31 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
java.lang.IllegalArgumentException: message is empty
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:205)
        at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:80)
        at org.itxtech.mirainative.bridge.MiraiBridge$sendPrivateMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:145)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```

大佬，请问这个报错怎么解决？

**Comment by khjxiaogu** [comment]
1、mirai\data\点歌插件\config.yml
2、我不认为这是需要的东西，所以短期内不会做支持

**Comment by khjxiaogu** [comment]
> ```
> 2021-06-18 21:03:31 E/MiraiNative: Exception in coroutine Plugin MiraiNative of MiraiNative
> java.lang.IllegalArgumentException: message is empty
>         at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:205)
>         at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:80)
>         at org.itxtech.mirainative.bridge.MiraiBridge$sendPrivateMessage$$inlined$call$lambda$1.invokeSuspend(MiraiBridge.kt:145)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```
> 
> 大佬，请问这个报错怎么解决？
请咨询MiraiNative的作者解决问题。
