### ISSUE TITLE
[Bug] 修改配置文件重启后就不能用了

### ISSUE THREAD

**Issue by lowerbound123** [khjxiaogu/MiraiSongPlugin#45]
### 错误现像描述

2022-04-19 20:47:48 E/点歌插件: java.util.NoSuchElementException: ffmpeg_path
java.util.NoSuchElementException: ffmpeg_path
        at net.mamoe.yamlkt.YamlMap.getOrFail(YamlElement.kt:292)
        at net.mamoe.yamlkt.YamlMap.getString(YamlElement.kt:305)
        at com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.reload(MiraiSongPlugin.java:437)
        at com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.onEnable(MiraiSongPlugin.java:276)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:117)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:164)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:36)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:47)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:135)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:177)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:202)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:401)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:156)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:155)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:88)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:78)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:100)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:145)
        at org.itxtech.mcl.Loader.lambda$start$3(Loader.java:170)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:138)
        at org.itxtech.mcl.Loader.start(Loader.java:170)
        at org.itxtech.mcl.Loader.main(Loader.java:75)

### 预计结果

呃，能用？

### 重现步骤

修改配置文件，然后重启后就会出错，无论改什么

### 插件版本

1.1.7

### mirai版本

2.10.0

### 系统信息

windows server 2019

**Comment by khjxiaogu** [comment]
请不要擅自删除配置文件里面没用的配置项，建议删除配置等待插件重新生成

**Comment by lowerbound123** [comment]
呃，问题是我没有删除任何内容，我只是把false改成了true，没有删除任何内容，包括修改admin也会报错
