### ISSUE TITLE
[Bug] PC客户端无法听语音

### ISSUE THREAD

**Issue by SkyFutu** [khjxiaogu/MiraiSongPlugin#57]
### 错误现像描述

大佬，PCQQ的语音听不了，只有一个红色感叹号，然后手机端可以听

### 预计结果

希望手机和pc都能听语音

### 重现步骤

按照文档正常安装部署

### 插件版本

2.7-1.2.1

### mirai版本

2.14.0

### 系统信息

server 2019 WIN

**Comment by khjxiaogu** [comment]
请仔细阅读README [配置项](https://github.com/khjxiaogu/MiraiSongPlugin#%E9%85%8D%E7%BD%AE%E9%A1%B9)并自行调整配置。

**Comment by SkyFutu** [comment]
> 请仔细阅读README [配置项](https://github.com/khjxiaogu/MiraiSongPlugin#%E9%85%8D%E7%BD%AE%E9%A1%B9)并自行调整配置。

大佬我根据配置项目来改但是会报错
2023-03-19 22:09:50 E/点歌插件: java.util.NoSuchElementException: ffmpeg_path
java.util.NoSuchElementException: ffmpeg_path
        at net.mamoe.yamlkt.YamlMap.getOrFail(YamlElement.kt:291)
        at net.mamoe.yamlkt.YamlMap.getString(YamlElement.kt:304)
        at MiraiSongPlugin-2.7-1.2.1.jar//com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.reload(MiraiSongPlugin.java:481)
        at MiraiSongPlugin-2.7-1.2.1.jar//com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.onEnable(MiraiSongPlugin.java:289)
        at net.mamoe.mirai.console.internal.plugin.JvmPluginInternal.internalOnEnable$mirai_console(JvmPluginInternal.kt:232)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:305)
        at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.enable(BuiltInJvmPluginLoaderImpl.kt:35)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt)
        at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.enable(JvmPluginLoader.kt:50)
        at net.mamoe.mirai.console.plugin.PluginManager.enablePlugin(PluginManager.kt:173)
        at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.enableAllLoadedPlugins$mirai_console(PluginManagerImpl.kt:181)
        at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:347)
        at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:496)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
        at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
        at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
        at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
        at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
        at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
        at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
        at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
        at org.itxtech.mcl.Loader.start(Loader.java:196)
        at org.itxtech.mcl.Loader.main(Loader.java:84)
        
       这是我的配置文件
       ffmpeg_path: "ffmpeg"
silkenc_path: "silk_v3_encoder"
adddefault: true
amrqualityshift: false
amrwb: true
use_custom_ffmpeg_command: false
custom_ffmpeg_command: "ffmpeg -i %input% -ab 23.85k -ar 16000 -ac 1 -acodec amr_wb -y %output%"
enable_local: false
verbose: true
hintsongnotfound: "无法找到歌曲。"
hintcarderror: "分享歌曲失败。"
hintnotemplate: "无法找到卡片。"
hintsourcenotfound: "无法找到来源。"
enableParser: 1
admins: 
  - 0
extracommands: 
  "#分享": 
    source: all
    card: Share
