### ISSUE TITLE
已安装ffmpeg但是还有解码器找不到

### ISSUE THREAD

**Issue by tlw00988** [khjxiaogu/MiraiSongPlugin#61]
### 错误现像描述

Unknown encoder 'amr_wb'
2024-09-08 20:06:10 W/stderr: java.io.FileNotFoundException: temp/wv1725797156127.amr (没有那个文件或目录)
2024-09-08 20:06:10 W/stderr:   at java.base/java.io.FileInputStream.open0(Native Method)
2024-09-08 20:06:10 W/stderr:   at java.base/java.io.FileInputStream.open(Unknown Source)
2024-09-08 20:06:10 W/stderr:   at java.base/java.io.FileInputStream.<init>(Unknown Source)
2024-09-08 20:06:10 W/stderr:   at MiraiSongPlugin-2.7-1.2.1.jar//com.khjxiaogu.MiraiSongPlugin.cardprovider.AmrVoiceProvider.process(AmrVoiceProvider.java:89)
2024-09-08 20:06:10 W/stderr:   at MiraiSongPlugin-2.7-1.2.1.jar//com.khjxiaogu.MiraiSongPlugin.MiraiSongPlugin.lambda$makeSearchesTemplate$2(MiraiSongPlugin.java:224)
2024-09-08 20:06:10 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
2024-09-08 20:06:10 W/stderr:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
2024-09-08 20:06:10 W/stderr:   at java.base/java.lang.Thread.run(Unknown Source)

系统为opensuse leap 15.6,已经安装ffmpeg

### 预计结果

一切正常

### 重现步骤

1.正常用zypper安装ffmpeg
2.在qq群使用语音命令
3.报错

### 插件版本

1.2.1

### mirai版本

2.16.0

### 系统信息

opensuse leap 15.6

### 提交前我已确定：

- [X] 我已阅读README，没有发现对应内容。
- [X] 我已在issue内搜索，没有发现已有的issue。

**Comment by tlw00988** [comment]
2025.06.12考古
opensuse的ffmpeg不带这解码器
~~什么玩意~~
